spring:
  application:
    name: msvc-worker

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}

  data:
    redis:
      host: ${REDIS_SERVER}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

server:
  port: 8081

mediastack:
  uri: ${MEDIASTACK_URI}
  access_key: ${MEDIASTACK_API_KEY}
  country: us
  limit: 25